### POST request
POST http://localhost:3000/jobs
Content-Type: application/json

{
  "customerEmail": "customer@jobsapp.com",
  "title": "Graphic Designer Needed",
  "description": "We are looking for a creative graphic designer to work on our new marketing materials.",
  "categories": [
    "Design",
    "Marketing"
  ],
  "subcategories": [
    "Graphic Design",
    "Branding"
  ],
  "budget": 500
}

### GET request (all)
GET http://localhost:3000/jobs

### GET request with id
GET http://localhost:3000/jobs/678ccb961dbab51bee6f726f

###PUT request with id
PUT http://localhost:3000/jobs/678d24b6805ed6211b7ed5f8
Content-Type: application/json

{
  "customerEmail": "customer@jobsapp.com",
  "companyEmail": "company@jobsapp.com",
  "title": "Updated Job Title",
  "description": "Updated description for the job.",
  "categories": [
    "Updated Category"
  ],
  "subcategories": [
    "Updated Subcategory"
  ],
  "budget": 1000
}

###DELETE request with id
DELETE http://localhost:3000/jobs/678ccb961dbab51bee6f726f

###POST request with id
POST http://localhost:3000/jobs/678d26fe805ed6211b7ed5fe
Content-Type: application/json

{
  "companyEmail": "company1@jobsapp.com"
}